(load-if-exists (f-expand "init-conveniences.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-unicode.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-theme.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-which-key.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-outshine.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-winnav.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-ivy.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-undo-tree.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-ibuffer.el" emacs-core-cfg-dir))
;; (load-if-exists (f-expand "init-spell-check.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-treemacs.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-hydra.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-try.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-pass.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-magit.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-regex.el" emacs-core-cfg-dir))
(load-if-exists (f-expand "init-pass.el" emacs-core-cfg-dir))
